import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import '../styles/SmallFeatures.css';
import Sand from '../images/Small features 1_sand.jpg';
import sustainability from '../images/Small features 1_artisan.jpg';
import Shipping from '../images/Small features 1_free shipping.jpg';
function Features1() {
    return (_jsx(_Fragment, { children: _jsxs("div", Object.assign({ className: "features-small" }, { children: [_jsxs("div", Object.assign({ className: "rectangle-parent" }, { children: [_jsx("img", { className: "frame-child", alt: "", src: Sand }), _jsxs("div", Object.assign({ className: "scratch-resistant-parent" }, { children: [_jsx("div", Object.assign({ className: "scratch-resistant" }, { children: "Scratch resistant" })), _jsx("div", Object.assign({ className: "our-scratch-resistant-frames" }, { children: "Our scratch-resistant frames are made to withstand daily wear and tear" }))] }))] })), _jsxs("div", Object.assign({ className: "rectangle-parent" }, { children: [_jsx("img", { className: "frame-child", alt: "", src: sustainability }), _jsxs("div", Object.assign({ className: "scratch-resistant-parent" }, { children: [_jsx("div", Object.assign({ className: "scratch-resistant" }, { children: "Handcrafted sustainability" })), _jsxs("div", Object.assign({ className: "our-scratch-resistant-frames" }, { children: [_jsx("p", Object.assign({ className: "look-and-feel" }, { children: "Look and feel your best" })), _jsx("p", Object.assign({ className: "look-and-feel" }, { children: "while reducing your" })), _jsx("p", Object.assign({ className: "look-and-feel" }, { children: "carbon footprint" }))] }))] }))] })), _jsxs("div", Object.assign({ className: "rectangle-parent" }, { children: [_jsx("img", { className: "frame-child", alt: "", src: Shipping }), _jsxs("div", Object.assign({ className: "scratch-resistant-parent" }, { children: [_jsx("div", Object.assign({ className: "scratch-resistant" }, { children: "Always free shipping" })), _jsx("div", Object.assign({ className: "our-scratch-resistant-frames" }, { children: "Enjoy our eco-friendly shipping for free" }))] }))] }))] })) }));
}
export default Features1;
//# sourceMappingURL=SmallFeatures.js.map