import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import '../styles/SmFeatures2.css';
import uv from '../images/Small features 2_uv.jpg';
import prescription from '../images/Small features 2_prescription.jpg';
import sizes from '../images/Small features 2_sizes.jpg';
function Features2() {
    return (_jsx(_Fragment, { children: _jsxs("div", Object.assign({ className: "features-small-2" }, { children: [_jsxs("div", Object.assign({ className: "rectangle-parent-2" }, { children: [_jsx("img", { className: "frame-child-2", alt: "Uv-protection", src: uv }), _jsxs("div", Object.assign({ className: "scratch-resistant-parent-2" }, { children: [_jsx("div", Object.assign({ className: "scratch-resistant-2" }, { children: "100% UV protection" })), _jsx("div", Object.assign({ className: "our-scratch-resistant-frames-2" }, { children: "Every pair offers 100% UV protection, ensuring your eyes are safe in the sun" }))] }))] })), _jsxs("div", Object.assign({ className: "rectangle-parent-2" }, { children: [_jsx("img", { className: "frame-child-2", alt: "", src: prescription }), _jsxs("div", Object.assign({ className: "scratch-resistant-parent-2" }, { children: [_jsx("div", Object.assign({ className: "scratch-resistant-2" }, { children: _jsx("p", Object.assign({ className: "look-and-feel-2" }, { children: "All frames available as prescription glasses" })) })), _jsx("div", Object.assign({ className: "our-scratch-resistant-frames-2" }, { children: _jsx("p", Object.assign({ className: "look-and-feel-2" }, { children: "Frames for fashion, lenses for function- all styles fit for your prescription" })) }))] }))] })), _jsxs("div", Object.assign({ className: "rectangle-parent-2" }, { children: [_jsx("img", { className: "frame-child-2", alt: "", src: sizes }), _jsxs("div", Object.assign({ className: "scratch-resistant-parent-2" }, { children: [_jsx("div", Object.assign({ className: "scratch-resistant-2" }, { children: "Different sizes" })), _jsx("div", Object.assign({ className: "our-scratch-resistant-frames-2" }, { children: "Our frames comes in three sizes to provide the perfect fit" }))] }))] }))] })) }));
}
export default Features2;
//# sourceMappingURL=SmFeatures2.js.map